### ISSUE TITLE
cap deploy fails with "NoMethodError: undefined method `filter'"

### ISSUE THREAD

**Issue by toob** [linyows/capistrano-withrsync#11]
Hi!

Thanks a lot for capistrano-withrsync.

Here is a quick feedback if it could help (i'm not any good on github nor on ruby...).
The problem is probably on my side (wrong version, missing capistrano configuration, ...)

```
cap production deploy --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke deploy (first_time)
** Execute deploy
** Invoke deploy:starting (first_time)
** Execute deploy:starting
** Invoke deploy:check (first_time)
** Invoke rsync:override_scm (first_time)
[...]
** Execute git:create_release
** Invoke rsync:release (first_time)
** Invoke rsync:sync (first_time)
** Invoke rsync:stage (first_time)
** Invoke rsync:create_src (first_time)
** Execute rsync:create_src
** Execute rsync:stage
DEBUG [73b251ac] Running /usr/bin/env if test ! -d tmp/deploy; then echo "Directory does not exist 'tmp/deploy'" 1>&2; false; fi on
DEBUG [73b251ac] Command: if test ! -d tmp/deploy; then echo "Directory does not exist 'tmp/deploy'" 1>&2; false; fi
DEBUG [73b251ac] Finished in 0.002 seconds with exit status 0 (successful).
 INFO [d309d66a] Running /usr/bin/env git fetch --quiet --all --prune on
DEBUG [d309d66a] Command: cd tmp/deploy && /usr/bin/env git fetch --quiet --all --prune
 INFO [d309d66a] Finished in 0.270 seconds with exit status 0 (successful).
 INFO [ada11e66] Running /usr/bin/env git reset --hard origin/master on
DEBUG [ada11e66] Command: cd tmp/deploy && /usr/bin/env git reset --hard origin/master
DEBUG [ada11e66]     HEAD is now at bd360b4 change repository url
 INFO [ada11e66] Finished in 0.005 seconds with exit status 0 (successful).
** Execute rsync:sync
cap aborted!
NoMethodError: undefined method `filter' for #<Capistrano::Configuration:0x000000021e21c8>
/var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake:87:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake:86:in `each'
/var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake:86:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/capistrano/dsl.rb:15:in `invoke'
/var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake:37:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/capistrano/dsl.rb:15:in `invoke'
/usr/lib/ruby/vendor_ruby/capistrano/tasks/deploy.rake:9:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/capistrano/dsl.rb:15:in `invoke'
/usr/lib/ruby/vendor_ruby/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/capistrano/tasks/framework.rake:64:in `each'
/usr/lib/ruby/vendor_ruby/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/lib/ruby/vendor_ruby/capistrano/application.rb:15:in `run'
/usr/bin/cap:3:in `<main>'
Tasks: TOP => rsync:release => rsync:sync
The deploy has failed with an error: #<NoMethodError: undefined method `filter' for #<Capistrano::Configuration:0x000000021e21c8>>
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

As a quick and dirty patch (just to unblock me without understanding...) I did

```
diff /var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake /var/lib/gems/2.1.0/gems/capistrano-withrsync-0.1.2/lib/capistrano/tasks/withrsync.rake.ori
87c87
< #      unless Capistrano::Configuration.env.filter(role).roles_array.empty?
---
>       unless Capistrano::Configuration.env.filter(role).roles_array.empty?
99c99
< #      end
---
>       end
```

```
$ ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

$ cap --version
Capistrano Version: 3.2.1 (Rake Version: 10.3.2)

$ rsync --version
rsync  version 3.1.1  protocol version 31
Copyright (C) 1996-2014 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

Thanks

Bye

/toob

**Comment by kazu69** [comment]
Hi @toob

I had a same problem.
I solved the problem by using a ```capistrano version 3.4.0.```

If when you can not upgrade,  please try the following.

```diff
diff --git a/lib/capistrano/tasks/withrsync.rake b/lib/capistrano/tasks/withrsync.rake
index ea0c8d0..85cd3e3 100644
--- a/lib/capistrano/tasks/withrsync.rake
+++ b/lib/capistrano/tasks/withrsync.rake
@@ -84,7 +84,7 @@ namespace :rsync do
   task sync: :'rsync:stage' do
     last_rsync_to = nil
     release_roles(:all).each do |role|
-      unless Capistrano::Configuration.env.filter(role).roles_array.empty?
+      unless role.roles_array.empty?
         run_locally do
           user = "#{role.user}@" if !role.user.nil?
           rsync_options = "#{fetch(:rsync_options).join(' ')}"
```

https://github.com/linyows/capistrano-withrsync/commit/7d1e599e264c117060a067111df4dcb61d5bfed4

**Comment by linyows** [comment]
@kazu69 Thanks!

**Comment by linyows** [comment]
I'll fix later.

**Comment by linyows** [comment]
Please try this version https://github.com/linyows/capistrano-withrsync/releases/tag/v0.2.3.
